<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <script type="text/javascript">
        // var myPromise = new Promise(function(resolve, reject) {
        //     // 當异步代码执行成功时，我们才会调用resolve(...)，当异步代码失败时就会调用reject(...)
        //     // 本例中，使用setTimeout(...)模拟异步代码
        //     setTimeout(function () {
        //         // resolve('成功')
        //         reject('失败')
        //     },600)
        // });
        // myPromise.then(function (successMessage) {
        //     // successMessage是上面调用resolve(...)方法传入的值
        //     // successMessage参数不一定非要是字符串类型，这里是举例
        //     console.log('yeah!' + successMessage);
        // }).catch(function (reason) {
        //     console.log(reason);
        // })
    </script>
    <div id="log"></div>
    <button type="button" onclick='testPromise()'>test</button>
    <script type="text/javascript">
        'use strict';
        var promiseCount = 0;

        function testPromise() {
            var thisPromiseCount = ++promiseCount;

            var log = document.getElementById('log');
            log.insertAdjacentHTML('beforeend', thisPromiseCount +
                ') Started (<small>Sync code started</small>)<br/>');

            // 新建一个Promise对象
            var p1 = new Promise(
                function(resolve, reject) {
                    log.insertAdjacentHTML('beforeend', thisPromiseCount +
                        ') Promise started (<small>Async code started</small>)<br/>');
                    // 模拟异步代码
                    window.setTimeout(
                        function() {
                            // 填充（fulfilled））promise
                            if(true){
                                resolve(thisPromiseCount);
                            }else{
                                reject('注入错误信息');
                            }
                        }, Math.random() * 2000 + 1000
                    );
                }
            );

            // 通过调用then方法，我们定义了当promise被成功解析（resolved）/填充（fulfilled）时要执行的代码,
            // 而catch()方法则定义了当promise被拒绝（rejected）时要执行的代码.
            p1.then(
                // 记录被填充的值
                function(val) {
                    log.insertAdjacentHTML('beforeend', val +
                        ') Promise fulfilled (<small>Async code terminated</small>)<br/>');
                }
            )
            .catch(
                // 记录被拒绝的理由（异常信息）
                function(reason) {
                    console.log('Handle rejected promise ('+reason+') here.');
                }
            );

            log.insertAdjacentHTML('beforeend', thisPromiseCount +
                ') Promise made (<small>Sync code terminated</small>)<br/>');
        }
    </script>
</body>
</html>
